import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

export type AuditAction =
  | 'LOGIN'
  | 'LOGIN_FAILED'
  | 'TOKEN_REFRESH'
  | 'CREATE_LEAD'
  | 'VIEW_LEAD'
  | 'DELETE_LEAD'
  | 'EXPORT_DATA'
  | 'UPDATE_QUALIFICATION'
  | 'MOVE_PIPELINE'
  | 'CREATE_USER'
  | 'UPDATE_USER'
  | 'PASSWORD_RESET_REQUESTED'
  | 'PASSWORD_RESET_COMPLETED'
  | 'PLATFORM_ADMIN_LOGIN'
  | 'PLATFORM_CREATE_TENANT'
  | 'PLATFORM_SUSPEND_TENANT'
  | 'PLATFORM_ACTIVATE_TENANT'
  | 'PLATFORM_CHANGE_PLAN'
  | 'PLATFORM_IMPERSONATE'
  | 'PLATFORM_EXPORT_TENANT_DATA'
  | 'PLATFORM_UPDATE_TENANT'
  | 'PLATFORM_CREATE_USER'
  | 'PLATFORM_UPDATE_USER'
  | 'PLATFORM_TOGGLE_USER'
  | 'PLATFORM_RESET_USER_PASSWORD'
  | 'PLATFORM_DELETE_USER'
  | 'PLATFORM_CREATE_AGENT_TEMPLATE'
  | 'PLATFORM_UPDATE_AGENT_TEMPLATE'
  | 'PLATFORM_DELETE_AGENT_TEMPLATE'
  | 'PLATFORM_PUSH_AGENT_TEMPLATE'
  | 'PLATFORM_QUEUE_RECOVER'
  | 'PLATFORM_UPDATE_CONFIG'
  | 'PLAN_UPDATED'
  | 'ADDON_UPDATED'
  | 'TENANT_PLAN_CHANGED'
  | 'TENANT_LIMITS_OVERRIDE'
  | 'TENANT_ADDON_ADDED'
  | 'TENANT_ADDON_REMOVED'
  | 'LEAD_MERGE'
  | 'ASSIGN_LEAD'
  | 'UNIT_STATUS_CHANGED'
  | 'UNLINK_UNIT'
  | 'PRE_OCUPACAO_ATIVAR_FAMILIA'
  | 'PRE_OCUPACAO_MARCAR_FALTA'
  | 'PRE_OCUPACAO_ENCERRAR_DEMANDA'
  | 'PRE_OCUPACAO_GERAR_ENTREGAVEL'
  | 'PRE_OCUPACAO_ENVIAR_ENTREGAVEL'
  | 'PORTAL_FAMILIA_LOGIN'
  | 'PORTAL_FAMILIA_LOGIN_FAILED'
  | 'PLATFORM_FIN_CREATE_ENTRY'
  | 'PLATFORM_FIN_UPDATE_ENTRY'
  | 'PLATFORM_FIN_CANCEL_ENTRY'
  | 'PLATFORM_FIN_PAYMENT'
  | 'PLATFORM_FIN_PAYMENT_REVERSAL'
  | 'PLATFORM_FIN_UPDATE_RECURRING'
  | 'PLATFORM_FIN_GENERATE_RECURRING'
  | 'PLATFORM_FIN_IMPORT_STATEMENT'
  | 'PLATFORM_FIN_RECONCILE'
  | 'PLATFORM_FIN_UPLOAD_DOCUMENT'
  | 'PLATFORM_FIN_DELETE_DOCUMENT'
  | 'PLATFORM_FIN_DOC_GENERATE_ENTRIES';

@Injectable()
export class AuditService {
  constructor(private readonly prisma: PrismaService) {}

  async log(entry: {
    tenantId?: string;
    userId?: string;
    platformAdminId?: string;
    action: AuditAction;
    resourceType?: string;
    resourceId?: string;
    ipAddress?: string;
    metadata?: Record<string, any>;
  }) {
    try {
      await this.prisma.auditLog.create({ data: entry });
    } catch {
      // Audit log nunca pode quebrar o fluxo principal
    }
  }
}
